import { TemplateDefinition } from "../types";

export const DEFAULT_CERTIFICATE_TEMPLATE: TemplateDefinition = {
  version: "1.0",
  width: 1920,
  height: 1080,
  backgroundColor: "#09090b", // Deep luxury dark slate
  backgroundFit: "cover",
  elements: [
    // Outer Luxury Gold Border Frame
    {
      id: "outer-border",
      type: "shape",
      shapeType: "rectangle",
      x: 40,
      y: 40,
      width: 1840,
      height: 1000,
      fill: "#0c0a09",
      borderRadius: 28,
      stroke: "#d97706",
      strokeWidth: 4,
      zIndex: 0,
    },
    // Inner Accent Frame
    {
      id: "inner-border",
      type: "shape",
      shapeType: "rectangle",
      x: 65,
      y: 65,
      width: 1790,
      height: 950,
      fill: "transparent",
      borderRadius: 20,
      stroke: "#78350f",
      strokeWidth: 2,
      zIndex: 0,
    },

    // Header Branding
    {
      id: "cert-brand",
      type: "text",
      content: "ZERO ENGLISH ACADEMY",
      x: 200,
      y: 110,
      width: 1520,
      height: 40,
      fontFamily: "Inter",
      fontSize: 24,
      fontWeight: 800,
      color: "#fbbf24",
      textAlign: "center",
      letterSpacing: 6,
      zIndex: 2,
    },
    {
      id: "cert-main-title",
      type: "text",
      content: "CERTIFICATE OF CONTRIBUTION",
      x: 200,
      y: 160,
      width: 1520,
      height: 60,
      fontFamily: "Inter",
      fontSize: 46,
      fontWeight: 800,
      color: "#ffffff",
      textAlign: "center",
      letterSpacing: 4,
      zIndex: 2,
    },
    {
      id: "cert-subtitle",
      type: "text",
      content: "THIS IS PROUDLY PRESENTED TO",
      x: 200,
      y: 245,
      width: 1520,
      height: 30,
      fontFamily: "Inter",
      fontSize: 16,
      fontWeight: 600,
      color: "#a1a1aa",
      textAlign: "center",
      letterSpacing: 4,
      zIndex: 2,
    },

    // Contributor Name Line
    {
      id: "contributor-name",
      type: "dynamic-text",
      field: "{{contributor.name}}",
      content: "{{contributor.name}}",
      x: 200,
      y: 290,
      width: 1520,
      height: 75,
      fontFamily: "Hind Siliguri",
      fontSize: 56,
      fontWeight: 800,
      color: "#fde68a",
      textAlign: "center",
      zIndex: 2,
    },

    // Decorative underline
    {
      id: "name-line",
      type: "line",
      orientation: "horizontal",
      x: 660,
      y: 380,
      width: 600,
      height: 3,
      stroke: "#d97706",
      strokeWidth: 3,
      zIndex: 2,
    },

    // Contribution Narrative
    {
      id: "cert-body",
      type: "text",
      content: "In sincere appreciation of outstanding dedication, knowledge sharing, and exemplary contributions to the Zero English community, helping thousands of learners conquer English vocabulary and language skills.",
      x: 320,
      y: 420,
      width: 1280,
      height: 80,
      fontFamily: "Inter",
      fontSize: 22,
      fontWeight: 400,
      color: "#d4d4d8",
      textAlign: "center",
      lineHeight: 1.5,
      zIndex: 2,
    },

    // Metric Stats Card 1: Words Added
    {
      id: "stat-words-bg",
      type: "shape",
      shapeType: "rectangle",
      x: 400,
      y: 560,
      width: 320,
      height: 140,
      fill: "#1c1917",
      borderRadius: 20,
      stroke: "#44403c",
      strokeWidth: 1,
      zIndex: 1,
    },
    {
      id: "stat-words-val",
      type: "dynamic-text",
      field: "{{contributor.wordCount}}",
      content: "{{contributor.wordCount}}",
      x: 400,
      y: 580,
      width: 320,
      height: 50,
      fontFamily: "Inter",
      fontSize: 42,
      fontWeight: 800,
      color: "#38bdf8",
      textAlign: "center",
      zIndex: 2,
    },
    {
      id: "stat-words-lbl",
      type: "text",
      content: "Vocabulary Words Added",
      x: 400,
      y: 645,
      width: 320,
      height: 25,
      fontFamily: "Inter",
      fontSize: 16,
      fontWeight: 600,
      color: "#a1a1aa",
      textAlign: "center",
      zIndex: 2,
    },

    // Metric Stats Card 2: Quizzes Added
    {
      id: "stat-quiz-bg",
      type: "shape",
      shapeType: "rectangle",
      x: 800,
      y: 560,
      width: 320,
      height: 140,
      fill: "#1c1917",
      borderRadius: 20,
      stroke: "#44403c",
      strokeWidth: 1,
      zIndex: 1,
    },
    {
      id: "stat-quiz-val",
      type: "dynamic-text",
      field: "{{contributor.quizCount}}",
      content: "{{contributor.quizCount}}",
      x: 800,
      y: 580,
      width: 320,
      height: 50,
      fontFamily: "Inter",
      fontSize: 42,
      fontWeight: 800,
      color: "#4ade80",
      textAlign: "center",
      zIndex: 2,
    },
    {
      id: "stat-quiz-lbl",
      type: "text",
      content: "Quiz Questions Added",
      x: 800,
      y: 645,
      width: 320,
      height: 25,
      fontFamily: "Inter",
      fontSize: 16,
      fontWeight: 600,
      color: "#a1a1aa",
      textAlign: "center",
      zIndex: 2,
    },

    // Metric Stats Card 3: Total Impact
    {
      id: "stat-total-bg",
      type: "shape",
      shapeType: "rectangle",
      x: 1200,
      y: 560,
      width: 320,
      height: 140,
      fill: "#1c1917",
      borderRadius: 20,
      stroke: "#44403c",
      strokeWidth: 1,
      zIndex: 1,
    },
    {
      id: "stat-total-val",
      type: "dynamic-text",
      field: "{{contributor.contributionCount}}",
      content: "{{contributor.contributionCount}}",
      x: 1200,
      y: 580,
      width: 320,
      height: 50,
      fontFamily: "Inter",
      fontSize: 42,
      fontWeight: 800,
      color: "#fbbf24",
      textAlign: "center",
      zIndex: 2,
    },
    {
      id: "stat-total-lbl",
      type: "text",
      content: "Total Verified Contributions",
      x: 1200,
      y: 645,
      width: 320,
      height: 25,
      fontFamily: "Inter",
      fontSize: 16,
      fontWeight: 600,
      color: "#a1a1aa",
      textAlign: "center",
      zIndex: 2,
    },

    // Footer: Issue Date (Left)
    {
      id: "footer-date-val",
      type: "dynamic-text",
      field: "{{contributor.issueDate}}",
      content: "{{contributor.issueDate}}",
      x: 200,
      y: 830,
      width: 350,
      height: 30,
      fontFamily: "Inter",
      fontSize: 18,
      fontWeight: 700,
      color: "#ffffff",
      textAlign: "left",
      zIndex: 2,
    },
    {
      id: "footer-date-lbl",
      type: "text",
      content: "DATE OF ISSUANCE",
      x: 200,
      y: 865,
      width: 350,
      height: 20,
      fontFamily: "Inter",
      fontSize: 12,
      fontWeight: 700,
      color: "#71717a",
      textAlign: "left",
      letterSpacing: 2,
      zIndex: 2,
    },

    // Footer: QR Verification (Center)
    {
      id: "footer-qr",
      type: "qrcode",
      field: "{{contributor.profileUrl}}",
      x: 885,
      y: 770,
      width: 150,
      height: 150,
      darkColor: "#000000",
      lightColor: "#ffffff",
      zIndex: 2,
    },
    {
      id: "footer-qr-lbl",
      type: "text",
      content: "SCAN TO VERIFY CREDENTIAL",
      x: 760,
      y: 935,
      width: 400,
      height: 20,
      fontFamily: "Inter",
      fontSize: 12,
      fontWeight: 700,
      color: "#71717a",
      textAlign: "center",
      letterSpacing: 2,
      zIndex: 2,
    },

    // Footer: Serial ID & Signature (Right)
    {
      id: "footer-serial-val",
      type: "dynamic-text",
      field: "{{contributor.certificateId}}",
      content: "{{contributor.certificateId}}",
      x: 1370,
      y: 830,
      width: 350,
      height: 30,
      fontFamily: "Inter",
      fontSize: 18,
      fontWeight: 700,
      color: "#fbbf24",
      textAlign: "right",
      zIndex: 2,
    },
    {
      id: "footer-serial-lbl",
      type: "text",
      content: "VERIFICATION SERIAL ID",
      x: 1370,
      y: 865,
      width: 350,
      height: 20,
      fontFamily: "Inter",
      fontSize: 12,
      fontWeight: 700,
      color: "#71717a",
      textAlign: "right",
      letterSpacing: 2,
      zIndex: 2,
    },
  ],
};
