import { DynamicFieldDefinition, TemplateType } from "./types";
import { SITE_NAME } from "@/lib/site-config";

export const DYNAMIC_FIELDS_REGISTRY: DynamicFieldDefinition[] = [
  // Quiz Fields
  {
    key: "{{quiz.id}}",
    label: "Quiz ID (#)",
    category: "QUIZ_POSTER",
    sampleValue: "1056",
    type: "text",
    description: "Numeric ID of the question",
  },
  {
    key: "{{quiz.question}}",
    label: "Question Text",
    category: "QUIZ_POSTER",
    sampleValue: "What is the synonym of 'Abundant'?",
    type: "text",
    description: "Main question sentence",
  },
  {
    key: "{{quiz.optionA}}",
    label: "Option A",
    category: "QUIZ_POSTER",
    sampleValue: "Plentiful",
    type: "text",
    description: "First answer choice",
  },
  {
    key: "{{quiz.optionB}}",
    label: "Option B",
    category: "QUIZ_POSTER",
    sampleValue: "Scarce",
    type: "text",
    description: "Second answer choice",
  },
  {
    key: "{{quiz.optionC}}",
    label: "Option C",
    category: "QUIZ_POSTER",
    sampleValue: "Meager",
    type: "text",
    description: "Third answer choice",
  },
  {
    key: "{{quiz.optionD}}",
    label: "Option D",
    category: "QUIZ_POSTER",
    sampleValue: "Insufficient",
    type: "text",
    description: "Fourth answer choice",
  },
  {
    key: "{{quiz.answer}}",
    label: "Correct Answer",
    category: "QUIZ_POSTER",
    sampleValue: "Plentiful",
    type: "text",
    description: "The verified correct answer text",
  },
  {
    key: "{{quiz.explanation}}",
    label: "Explanation",
    category: "QUIZ_POSTER",
    sampleValue: "'Abundant' means existing or available in large quantities; plentiful.",
    type: "text",
    description: "Detailed explanation or hint",
  },
  {
    key: "{{quiz.category}}",
    label: "Category / Type",
    category: "QUIZ_POSTER",
    sampleValue: "Vocabulary",
    type: "text",
    description: "Quiz category or topic",
  },
  {
    key: "{{quiz.difficulty}}",
    label: "Difficulty Level",
    category: "QUIZ_POSTER",
    sampleValue: "Medium",
    type: "text",
    description: "EASY, MEDIUM, or HARD",
  },
  {
    key: "{{quiz.authorName}}",
    label: "Added By (Name)",
    category: "QUIZ_POSTER",
    sampleValue: "Tanvir Ahmed",
    type: "text",
    description: "Name of the question contributor",
  },
  {
    key: "{{quiz.url}}",
    label: "Quiz Web URL / QR Target",
    category: "QUIZ_POSTER",
    sampleValue: "https://zeroenglish.org/quiz/question/1056",
    type: "url",
    description: "Direct web link to open and solve the quiz",
  },

  // Contributor Certificate Fields
  {
    key: "{{contributor.name}}",
    label: "Contributor Full Name",
    category: "CONTRIBUTOR_CERTIFICATE",
    sampleValue: "Tanvir Ahmed",
    type: "text",
    description: "Full display name of the contributor",
  },
  {
    key: "{{contributor.username}}",
    label: "Username",
    category: "CONTRIBUTOR_CERTIFICATE",
    sampleValue: "@tanvir_eng",
    type: "text",
    description: "Unique handle of the contributor",
  },
  {
    key: "{{contributor.role}}",
    label: "Role / Title",
    category: "CONTRIBUTOR_CERTIFICATE",
    sampleValue: "Senior Contributor",
    type: "text",
    description: "Contributor or Admin designation",
  },
  {
    key: "{{contributor.profilePhoto}}",
    label: "Profile Photo",
    category: "CONTRIBUTOR_CERTIFICATE",
    sampleValue: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop",
    type: "image",
    description: "Avatar / profile photo image URL",
  },
  {
    key: "{{contributor.contributionCount}}",
    label: "Total Contributions",
    category: "CONTRIBUTOR_CERTIFICATE",
    sampleValue: "142",
    type: "text",
    description: "Total combined words and questions contributed",
  },
  {
    key: "{{contributor.wordCount}}",
    label: "Vocabulary Words Added",
    category: "CONTRIBUTOR_CERTIFICATE",
    sampleValue: "98",
    type: "text",
    description: "Number of approved vocabulary words",
  },
  {
    key: "{{contributor.quizCount}}",
    label: "Quiz Questions Added",
    category: "CONTRIBUTOR_CERTIFICATE",
    sampleValue: "44",
    type: "text",
    description: "Number of approved quiz questions",
  },
  {
    key: "{{contributor.issueDate}}",
    label: "Certificate Issue Date",
    category: "CONTRIBUTOR_CERTIFICATE",
    sampleValue: "October 8, 2026",
    type: "text",
    description: "Formatted date of generation",
  },
  {
    key: "{{contributor.certificateId}}",
    label: "Certificate Serial Number",
    category: "CONTRIBUTOR_CERTIFICATE",
    sampleValue: "ZE-CERT-2026-0814",
    type: "text",
    description: "Unique serial code for authentication",
  },
  {
    key: "{{contributor.profileUrl}}",
    label: "Contributor Profile Link",
    category: "CONTRIBUTOR_CERTIFICATE",
    sampleValue: "https://zeroenglish.org/profile/42",
    type: "url",
    description: "Direct web link to contributor profile",
  },

  // Vocabulary Poster Fields
  {
    key: "{{vocab.id}}",
    label: "Word ID (#)",
    category: "VOCABULARY_POSTER",
    sampleValue: "342",
    type: "text",
    description: "Numeric database ID of the vocabulary word",
  },
  {
    key: "{{vocab.word}}",
    label: "English Word",
    category: "VOCABULARY_POSTER",
    sampleValue: "Eloquent",
    type: "text",
    description: "Primary English target word",
  },
  {
    key: "{{vocab.phonetic}}",
    label: "Phonetic / Pronunciation",
    category: "VOCABULARY_POSTER",
    sampleValue: "/ˈel.ə.kwənt/",
    type: "text",
    description: "IPA phonetic spelling / pronunciation guide",
  },
  {
    key: "{{vocab.partOfSpeech}}",
    label: "Part of Speech",
    category: "VOCABULARY_POSTER",
    sampleValue: "Adjective",
    type: "text",
    description: "Noun, Verb, Adjective, Adverb, etc.",
  },
  {
    key: "{{vocab.meaningBangla}}",
    label: "Bengali Meaning",
    category: "VOCABULARY_POSTER",
    sampleValue: "বাকপটু / সুন্দরভাবে কথা বলতে পারে এমন",
    type: "text",
    description: "Bengali definition or direct translation",
  },
  {
    key: "{{vocab.definition}}",
    label: "English Definition",
    category: "VOCABULARY_POSTER",
    sampleValue: "Fluent or persuasive in speaking or writing.",
    type: "text",
    description: "Clear dictionary explanation in English",
  },
  {
    key: "{{vocab.exampleSentence}}",
    label: "Example Sentence (EN)",
    category: "VOCABULARY_POSTER",
    sampleValue: "She gave an eloquent speech that inspired everyone in the hall.",
    type: "text",
    description: "Practical usage sentence in English",
  },
  {
    key: "{{vocab.exampleBangla}}",
    label: "Example Translation (BN)",
    category: "VOCABULARY_POSTER",
    sampleValue: "তিনি একটি বাকপটু ভাষণ দিয়েছিলেন যা হলের সবাইকে অনুপ্রাণিত করেছিল।",
    type: "text",
    description: "Bengali translation of the example sentence",
  },
  {
    key: "{{vocab.synonyms}}",
    label: "Synonyms",
    category: "VOCABULARY_POSTER",
    sampleValue: "Articulate, Fluent, Expressive, Persuasive",
    type: "text",
    description: "Similar meaning words",
  },
  {
    key: "{{vocab.antonyms}}",
    label: "Antonyms",
    category: "VOCABULARY_POSTER",
    sampleValue: "Inarticulate, Hesitant, Dull",
    type: "text",
    description: "Opposite meaning words",
  },
  {
    key: "{{vocab.level}}",
    label: "Difficulty Level",
    category: "VOCABULARY_POSTER",
    sampleValue: "ADVANCED",
    type: "text",
    description: "BEGINNER, INTERMEDIATE, or ADVANCED",
  },
  {
    key: "{{vocab.category}}",
    label: "Topic / Category",
    category: "VOCABULARY_POSTER",
    sampleValue: "Academic Vocabulary",
    type: "text",
    description: "Thematic category of the word",
  },
  {
    key: "{{vocab.url}}",
    label: "Word Web URL / QR Target",
    category: "VOCABULARY_POSTER",
    sampleValue: "https://zeroenglish.org/vocabulary/eloquent",
    type: "url",
    description: "Direct web link to study this word on Zero English",
  },

  // Leaderboard & Exam Ranking Fields
  {
    key: "{{leaderboard.rank}}",
    label: "Rank Position",
    category: "LEADERBOARD_POSTER",
    sampleValue: "#1 Champion",
    type: "text",
    description: "Leaderboard rank or standing position",
  },
  {
    key: "{{leaderboard.userName}}",
    label: "Participant Name",
    category: "LEADERBOARD_POSTER",
    sampleValue: "Tanvir Ahmed",
    type: "text",
    description: "Full name of the ranked user",
  },
  {
    key: "{{leaderboard.userPhoto}}",
    label: "User Avatar URL",
    category: "LEADERBOARD_POSTER",
    sampleValue: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop",
    type: "image",
    description: "Avatar image of the top participant",
  },
  {
    key: "{{leaderboard.score}}",
    label: "Total Score / Points",
    category: "LEADERBOARD_POSTER",
    sampleValue: "980 pts",
    type: "text",
    description: "Earned score points or exam marks",
  },
  {
    key: "{{leaderboard.accuracy}}",
    label: "Accuracy Rate",
    category: "LEADERBOARD_POSTER",
    sampleValue: "98%",
    type: "text",
    description: "Percentage of correct answers",
  },
  {
    key: "{{leaderboard.period}}",
    label: "Time Period / Title",
    category: "LEADERBOARD_POSTER",
    sampleValue: "Weekly Quiz Leaderboard",
    type: "text",
    description: "E.g. Weekly Leaderboard or Monthly Top Performers",
  },
  {
    key: "{{leaderboard.badge}}",
    label: "Achievement Badge",
    category: "LEADERBOARD_POSTER",
    sampleValue: "Grammar Master",
    type: "text",
    description: "Honorary badge or tier",
  },
  {
    key: "{{leaderboard.url}}",
    label: "Leaderboard Link",
    category: "LEADERBOARD_POSTER",
    sampleValue: "https://zeroenglish.org/leaderboard",
    type: "url",
    description: "Direct web link to live leaderboard",
  },

  // Social & Marketing Announcement Fields
  {
    key: "{{post.headline}}",
    label: "Headline / Quote",
    category: "SOCIAL_POST",
    sampleValue: "Daily English Tip: Master Phrasal Verbs",
    type: "text",
    description: "Primary post headline or motivational quote",
  },
  {
    key: "{{post.subheading}}",
    label: "Subheading / Context",
    category: "SOCIAL_POST",
    sampleValue: "Learn 5 new everyday phrasal verbs with clear examples & exercises.",
    type: "text",
    description: "Secondary descriptive text or supporting takeaway",
  },
  {
    key: "{{post.date}}",
    label: "Post Date",
    category: "SOCIAL_POST",
    sampleValue: "October 8, 2026",
    type: "text",
    description: "Current date formatted nicely",
  },
  {
    key: "{{post.callToAction}}",
    label: "Call to Action",
    category: "SOCIAL_POST",
    sampleValue: "Practice free quizzes now at zeroenglish.org",
    type: "text",
    description: "Call to action prompt for followers",
  },
  {
    key: "{{post.url}}",
    label: "Target Link / QR",
    category: "SOCIAL_POST",
    sampleValue: "https://zeroenglish.org",
    type: "url",
    description: "Direct link or QR destination",
  },

  // Global Brand & Platform Fields
  {
    key: "{{site.name}}",
    label: "Site Name",
    category: "ALL",
    sampleValue: SITE_NAME || "Zero English",
    type: "text",
    description: "Platform brand name",
  },
  {
    key: "{{site.url}}",
    label: "Site URL",
    category: "ALL",
    sampleValue: "https://zeroenglish.org",
    type: "url",
    description: "Platform homepage URL",
  },
  {
    key: "{{site.tagline}}",
    label: "Brand Tagline",
    category: "ALL",
    sampleValue: "Master English Without Fear",
    type: "text",
    description: "Official motto or slogan",
  },
  {
    key: "{{site.logo}}",
    label: "Brand Logo URL",
    category: "ALL",
    sampleValue: "https://zeroenglish.org/assets/logo/logo-full.webp",
    type: "image",
    description: "Official platform logo image asset",
  },
  {
    key: "{{site.callToAction}}",
    label: "Platform CTA",
    category: "ALL",
    sampleValue: "Start learning for free at zeroenglish.org",
    type: "text",
    description: "General call to action for social sharing",
  },
];

export function getFieldsForType(type: TemplateType | string): DynamicFieldDefinition[] {
  return DYNAMIC_FIELDS_REGISTRY.filter(
    (field) => field.category === "ALL" || field.category === type
  );
}

export function getSampleDataForType(type: TemplateType | string): Record<string, string> {
  const fields = getFieldsForType(type);
  const data: Record<string, string> = {};
  for (const field of fields) {
    data[field.key] = field.sampleValue;
  }
  return data;
}
