export type AdminUser = {
  id: number;
  name: string;
  email: string;
  role: "user" | "admin";
  level: "A1" | "A2" | "B1" | "B2";
  bookmarked: number;
  stillLearning: number;
  learned: number;
  quizResult: number;
  status: "Active" | "Inactive";
  joinedAt: string;
  lastActive: string;
  studyStreak: number;
  totalWordsStudied: number;
  bio: string;
  avatarColor: string;
  recentActivity: { action: string; date: string; detail: string }[];
  quizHistory: { quiz: string; score: number; total: number; date: string }[];
  monthlyProgress: { month: string; wordsLearned: number; quizAvg: number }[];
};

export const dummyUsers: AdminUser[] = [
  {
    id: 1,
    name: "Rahim Ahmed",
    email: "rahim@example.com",
    role: "user",
    level: "A2",
    bookmarked: 45,
    stillLearning: 120,
    learned: 342,
    quizResult: 78,
    status: "Active",
    joinedAt: "2025-09-15",
    lastActive: "2026-08-30",
    studyStreak: 14,
    totalWordsStudied: 507,
    bio: "Passionate about learning English vocabulary. Focuses on everyday conversational words.",
    avatarColor: "bg-blue-500",
    recentActivity: [
      { action: "Learned word", date: "2026-08-30", detail: "ubiquitous" },
      { action: "Took quiz", date: "2026-08-29", detail: "Score: 18/20" },
      { action: "Bookmarked word", date: "2026-08-28", detail: "ephemeral" },
      { action: "Completed level", date: "2026-08-25", detail: "A2 Section 4" },
      { action: "Learned word", date: "2026-08-24", detail: "pragmatic" },
    ],
    quizHistory: [
      { quiz: "A2 Vocabulary Test 1", score: 18, total: 20, date: "2026-08-29" },
      { quiz: "A2 Vocabulary Test 2", score: 15, total: 20, date: "2026-08-20" },
      { quiz: "A2 Grammar Quiz", score: 16, total: 20, date: "2026-08-12" },
      { quiz: "A1 Review Test", score: 20, total: 20, date: "2026-07-30" },
    ],
    monthlyProgress: [
      { month: "Apr", wordsLearned: 45, quizAvg: 72 },
      { month: "May", wordsLearned: 62, quizAvg: 75 },
      { month: "Jun", wordsLearned: 78, quizAvg: 78 },
      { month: "Jul", wordsLearned: 90, quizAvg: 80 },
      { month: "Aug", wordsLearned: 67, quizAvg: 78 },
    ],
  },
  {
    id: 2,
    name: "Fatema Begum",
    email: "fatema@example.com",
    role: "user",
    level: "B1",
    bookmarked: 89,
    stillLearning: 210,
    learned: 891,
    quizResult: 85,
    status: "Active",
    joinedAt: "2025-06-20",
    lastActive: "2026-08-31",
    studyStreak: 32,
    totalWordsStudied: 1190,
    bio: "Advanced learner preparing for IELTS. Focuses on academic vocabulary.",
    avatarColor: "bg-purple-500",
    recentActivity: [
      { action: "Learned word", date: "2026-08-31", detail: "serendipity" },
      { action: "Took quiz", date: "2026-08-30", detail: "Score: 19/20" },
      { action: "Learned word", date: "2026-08-29", detail: "melancholy" },
      { action: "Bookmarked word", date: "2026-08-28", detail: "eloquent" },
      { action: "Took quiz", date: "2026-08-27", detail: "Score: 17/20" },
    ],
    quizHistory: [
      { quiz: "B1 Vocabulary Test 1", score: 19, total: 20, date: "2026-08-30" },
      { quiz: "B1 Vocabulary Test 2", score: 17, total: 20, date: "2026-08-27" },
      { quiz: "B1 Idioms Quiz", score: 15, total: 20, date: "2026-08-18" },
      { quiz: "A2 Final Test", score: 20, total: 20, date: "2026-07-15" },
    ],
    monthlyProgress: [
      { month: "Apr", wordsLearned: 110, quizAvg: 80 },
      { month: "May", wordsLearned: 135, quizAvg: 82 },
      { month: "Jun", wordsLearned: 148, quizAvg: 84 },
      { month: "Jul", wordsLearned: 165, quizAvg: 85 },
      { month: "Aug", wordsLearned: 123, quizAvg: 85 },
    ],
  },
  {
    id: 3,
    name: "Karim Uddin",
    email: "karim@example.com",
    role: "user",
    level: "A1",
    bookmarked: 12,
    stillLearning: 80,
    learned: 120,
    quizResult: 55,
    status: "Inactive",
    joinedAt: "2026-01-10",
    lastActive: "2026-07-05",
    studyStreak: 0,
    totalWordsStudied: 212,
    bio: "Beginner learning English for work communication.",
    avatarColor: "bg-amber-500",
    recentActivity: [
      { action: "Learned word", date: "2026-07-05", detail: "airport" },
      { action: "Took quiz", date: "2026-07-03", detail: "Score: 11/20" },
      { action: "Bookmarked word", date: "2026-07-01", detail: " reservation" },
      { action: "Learned word", date: "2026-06-28", detail: "receipt" },
      { action: "Took quiz", date: "2026-06-25", detail: "Score: 9/20" },
    ],
    quizHistory: [
      { quiz: "A1 Vocabulary Test 1", score: 11, total: 20, date: "2026-07-03" },
      { quiz: "A1 Vocabulary Test 2", score: 9, total: 20, date: "2026-06-25" },
      { quiz: "A1 Basics Quiz", score: 14, total: 20, date: "2026-06-15" },
    ],
    monthlyProgress: [
      { month: "Apr", wordsLearned: 25, quizAvg: 50 },
      { month: "May", wordsLearned: 35, quizAvg: 52 },
      { month: "Jun", wordsLearned: 30, quizAvg: 55 },
      { month: "Jul", wordsLearned: 15, quizAvg: 55 },
      { month: "Aug", wordsLearned: 0, quizAvg: 0 },
    ],
  },
  {
    id: 4,
    name: "Nusrat Jahan",
    email: "nusrat@example.com",
    role: "user",
    level: "B2",
    bookmarked: 134,
    stillLearning: 180,
    learned: 1254,
    quizResult: 92,
    status: "Active",
    joinedAt: "2025-03-08",
    lastActive: "2026-08-31",
    studyStreak: 45,
    totalWordsStudied: 1568,
    bio: "English literature student. Loves learning nuanced and literary vocabulary.",
    avatarColor: "bg-rose-500",
    recentActivity: [
      { action: "Learned word", date: "2026-08-31", detail: "magnanimous" },
      { action: "Learned word", date: "2026-08-31", detail: "pernicious" },
      { action: "Took quiz", date: "2026-08-30", detail: "Score: 20/20" },
      { action: "Bookmarked word", date: "2026-08-29", detail: "perspicacious" },
      { action: "Completed level", date: "2026-08-20", detail: "B2 Section 6" },
    ],
    quizHistory: [
      { quiz: "B2 Vocabulary Test 1", score: 20, total: 20, date: "2026-08-30" },
      { quiz: "B2 Vocabulary Test 2", score: 19, total: 20, date: "2026-08-22" },
      { quiz: "B2 Advanced Quiz", score: 18, total: 20, date: "2026-08-14" },
      { quiz: "B1 Final Test", score: 20, total: 20, date: "2026-07-20" },
    ],
    monthlyProgress: [
      { month: "Apr", wordsLearned: 180, quizAvg: 88 },
      { month: "May", wordsLearned: 200, quizAvg: 90 },
      { month: "Jun", wordsLearned: 210, quizAvg: 91 },
      { month: "Jul", wordsLearned: 225, quizAvg: 92 },
      { month: "Aug", wordsLearned: 195, quizAvg: 92 },
    ],
  },
  {
    id: 5,
    name: "Tanjim Hasan",
    email: "tanjim@example.com",
    role: "user",
    level: "A2",
    bookmarked: 30,
    stillLearning: 95,
    learned: 478,
    quizResult: 72,
    status: "Active",
    joinedAt: "2025-11-22",
    lastActive: "2026-08-29",
    studyStreak: 8,
    totalWordsStudied: 603,
    bio: "Software developer improving English for better tech documentation reading.",
    avatarColor: "bg-emerald-500",
    recentActivity: [
      { action: "Learned word", date: "2026-08-29", detail: "syntax" },
      { action: "Took quiz", date: "2026-08-28", detail: "Score: 14/20" },
      { action: "Bookmarked word", date: "2026-08-27", detail: "refactor" },
      { action: "Learned word", date: "2026-08-26", detail: "deploy" },
      { action: "Took quiz", date: "2026-08-25", detail: "Score: 16/20" },
    ],
    quizHistory: [
      { quiz: "A2 Vocabulary Test 1", score: 14, total: 20, date: "2026-08-28" },
      { quiz: "A2 Vocabulary Test 2", score: 16, total: 20, date: "2026-08-25" },
      { quiz: "A2 Context Quiz", score: 13, total: 20, date: "2026-08-16" },
      { quiz: "A1 Final Test", score: 19, total: 20, date: "2026-08-01" },
    ],
    monthlyProgress: [
      { month: "Apr", wordsLearned: 55, quizAvg: 68 },
      { month: "May", wordsLearned: 70, quizAvg: 70 },
      { month: "Jun", wordsLearned: 85, quizAvg: 72 },
      { month: "Jul", wordsLearned: 100, quizAvg: 72 },
      { month: "Aug", wordsLearned: 88, quizAvg: 72 },
    ],
  },
  {
    id: 6,
    name: "Sumaiya Khatun",
    email: "sumaiya@example.com",
    role: "admin",
    level: "B2",
    bookmarked: 200,
    stillLearning: 50,
    learned: 1500,
    quizResult: 96,
    status: "Active",
    joinedAt: "2025-01-05",
    lastActive: "2026-08-31",
    studyStreak: 60,
    totalWordsStudied: 1750,
    bio: "Platform administrator and English teacher. Helps maintain the word database.",
    avatarColor: "bg-indigo-500",
    recentActivity: [
      { action: "Learned word", date: "2026-08-31", detail: "paradigm" },
      { action: "Took quiz", date: "2026-08-30", detail: "Score: 20/20" },
      { action: "Learned word", date: "2026-08-29", detail: "juxtapose" },
      { action: "Learned word", date: "2026-08-28", detail: "surreptitious" },
      { action: "Took quiz", date: "2026-08-27", detail: "Score: 19/20" },
    ],
    quizHistory: [
      { quiz: "B2 Vocabulary Test 1", score: 20, total: 20, date: "2026-08-30" },
      { quiz: "B2 Vocabulary Test 2", score: 19, total: 20, date: "2026-08-27" },
      { quiz: "B2 Mastery Quiz", score: 20, total: 20, date: "2026-08-18" },
      { quiz: "B1 Final Test", score: 20, total: 20, date: "2026-06-10" },
    ],
    monthlyProgress: [
      { month: "Apr", wordsLearned: 200, quizAvg: 94 },
      { month: "May", wordsLearned: 210, quizAvg: 95 },
      { month: "Jun", wordsLearned: 220, quizAvg: 96 },
      { month: "Jul", wordsLearned: 230, quizAvg: 96 },
      { month: "Aug", wordsLearned: 215, quizAvg: 96 },
    ],
  },
  {
    id: 7,
    name: "Arif Rahman",
    email: "arif@example.com",
    role: "user",
    level: "A1",
    bookmarked: 5,
    stillLearning: 40,
    learned: 55,
    quizResult: 42,
    status: "Inactive",
    joinedAt: "2026-04-18",
    lastActive: "2026-06-10",
    studyStreak: 0,
    totalWordsStudied: 100,
    bio: "Just started learning English from scratch.",
    avatarColor: "bg-teal-500",
    recentActivity: [
      { action: "Learned word", date: "2026-06-10", detail: "hello" },
      { action: "Took quiz", date: "2026-06-08", detail: "Score: 8/20" },
      { action: "Learned word", date: "2026-06-05", detail: "goodbye" },
      { action: "Bookmarked word", date: "2026-06-03", detail: "thank you" },
      { action: "Took quiz", date: "2026-06-01", detail: "Score: 6/20" },
    ],
    quizHistory: [
      { quiz: "A1 Vocabulary Test 1", score: 8, total: 20, date: "2026-06-08" },
      { quiz: "A1 First Quiz", score: 6, total: 20, date: "2026-06-01" },
    ],
    monthlyProgress: [
      { month: "Apr", wordsLearned: 15, quizAvg: 40 },
      { month: "May", wordsLearned: 25, quizAvg: 42 },
      { month: "Jun", wordsLearned: 15, quizAvg: 42 },
      { month: "Jul", wordsLearned: 0, quizAvg: 0 },
      { month: "Aug", wordsLearned: 0, quizAvg: 0 },
    ],
  },
  {
    id: 8,
    name: "Mst. Rabeya Akter",
    email: "rabeya@example.com",
    role: "user",
    level: "B1",
    bookmarked: 67,
    stillLearning: 150,
    learned: 720,
    quizResult: 80,
    status: "Active",
    joinedAt: "2025-08-12",
    lastActive: "2026-08-30",
    studyStreak: 21,
    totalWordsStudied: 937,
    bio: "University student studying English literature alongside her main major.",
    avatarColor: "bg-pink-500",
    recentActivity: [
      { action: "Learned word", date: "2026-08-30", detail: "ambivalent" },
      { action: "Took quiz", date: "2026-08-29", detail: "Score: 16/20" },
      { action: "Bookmarked word", date: "2026-08-28", detail: "catharsis" },
      { action: "Learned word", date: "2026-08-27", detail: "ennui" },
      { action: "Took quiz", date: "2026-08-26", detail: "Score: 15/20" },
    ],
    quizHistory: [
      { quiz: "B1 Vocabulary Test 1", score: 16, total: 20, date: "2026-08-29" },
      { quiz: "B1 Vocabulary Test 2", score: 15, total: 20, date: "2026-08-26" },
      { quiz: "B1 Context Quiz", score: 17, total: 20, date: "2026-08-18" },
      { quiz: "A2 Final Test", score: 18, total: 20, date: "2026-07-25" },
    ],
    monthlyProgress: [
      { month: "Apr", wordsLearned: 90, quizAvg: 76 },
      { month: "May", wordsLearned: 105, quizAvg: 78 },
      { month: "Jun", wordsLearned: 120, quizAvg: 79 },
      { month: "Jul", wordsLearned: 130, quizAvg: 80 },
      { month: "Aug", wordsLearned: 115, quizAvg: 80 },
    ],
  },
  {
    id: 9,
    name: "Sakib Chowdhury",
    email: "sakib@example.com",
    role: "user",
    level: "A2",
    bookmarked: 22,
    stillLearning: 70,
    learned: 310,
    quizResult: 68,
    status: "Active",
    joinedAt: "2026-02-28",
    lastActive: "2026-08-28",
    studyStreak: 5,
    totalWordsStudied: 402,
    bio: "High school student preparing for English exams.",
    avatarColor: "bg-cyan-500",
    recentActivity: [
      { action: "Learned word", date: "2026-08-28", detail: "hypothesis" },
      { action: "Took quiz", date: "2026-08-27", detail: "Score: 13/20" },
      { action: "Bookmarked word", date: "2026-08-26", detail: "theory" },
      { action: "Learned word", date: "2026-08-25", detail: "experiment" },
      { action: "Took quiz", date: "2026-08-24", detail: "Score: 14/20" },
    ],
    quizHistory: [
      { quiz: "A2 Vocabulary Test 1", score: 13, total: 20, date: "2026-08-27" },
      { quiz: "A2 Vocabulary Test 2", score: 14, total: 20, date: "2026-08-24" },
      { quiz: "A2 Science Words", score: 12, total: 20, date: "2026-08-15" },
      { quiz: "A1 Final Test", score: 17, total: 20, date: "2026-07-20" },
    ],
    monthlyProgress: [
      { month: "Apr", wordsLearned: 40, quizAvg: 65 },
      { month: "May", wordsLearned: 55, quizAvg: 66 },
      { month: "Jun", wordsLearned: 65, quizAvg: 67 },
      { month: "Jul", wordsLearned: 80, quizAvg: 68 },
      { month: "Aug", wordsLearned: 70, quizAvg: 68 },
    ],
  },
  {
    id: 10,
    name: "Tasnim Ahmed",
    email: "tasnim@example.com",
    role: "user",
    level: "B1",
    bookmarked: 55,
    stillLearning: 130,
    learned: 650,
    quizResult: 76,
    status: "Active",
    joinedAt: "2025-10-05",
    lastActive: "2026-08-30",
    studyStreak: 18,
    totalWordsStudied: 835,
    bio: "Working professional learning English for international business communication.",
    avatarColor: "bg-orange-500",
    recentActivity: [
      { action: "Learned word", date: "2026-08-30", detail: "negotiate" },
      { action: "Took quiz", date: "2026-08-29", detail: "Score: 15/20" },
      { action: "Bookmarked word", date: "2026-08-28", detail: "leverage" },
      { action: "Learned word", date: "2026-08-27", detail: "stakeholder" },
      { action: "Took quiz", date: "2026-08-26", detail: "Score: 16/20" },
    ],
    quizHistory: [
      { quiz: "B1 Vocabulary Test 1", score: 15, total: 20, date: "2026-08-29" },
      { quiz: "B1 Business Words", score: 16, total: 20, date: "2026-08-26" },
      { quiz: "B1 Vocabulary Test 2", score: 14, total: 20, date: "2026-08-18" },
      { quiz: "A2 Final Test", score: 18, total: 20, date: "2026-07-10" },
    ],
    monthlyProgress: [
      { month: "Apr", wordsLearned: 80, quizAvg: 73 },
      { month: "May", wordsLearned: 95, quizAvg: 74 },
      { month: "Jun", wordsLearned: 110, quizAvg: 75 },
      { month: "Jul", wordsLearned: 125, quizAvg: 76 },
      { month: "Aug", wordsLearned: 100, quizAvg: 76 },
    ],
  },
];

export function getUserById(id: number): AdminUser | undefined {
  return dummyUsers.find((u) => u.id === id);
}
