export type VocabularyWord = {
  id: number;
  word: string;
  meaningBn: string[];
  definitionEn: string;
  definitionBn: string;
  examplesEn: string[];
  examplesBn: string[];
  synonyms: string[];
  antonyms: string[];
  level: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
  category: string;
  partsOfSpeech: string;
};

export const levelOptions = ["A1", "A2", "B1", "B2", "C1", "C2"] as const;

export const partsOfSpeechOptions = [
  "noun",
  "verb",
  "adjective",
  "adverb",
  "pronoun",
  "preposition",
  "conjunction",
  "interjection",
  "article",
];

export const defaultCategories = ["Oxford3000", "Academic", "Business", "Travel", "Idioms"];

export const dummyVocabulary: VocabularyWord[] = [
  {
    id: 1,
    word: "abandon",
    meaningBn: ["পরিত্যাগ করা", "ছেড়ে দেওয়া"],
    definitionEn:
      "To leave someone or something permanently, especially when you should not.",
    definitionBn: "কোনো ব্যক্তি বা জিনিস স্থায়ীভাবে ছেড়ে যাওয়া।",
    examplesEn: [
      "The crew had to abandon the ship during the storm.",
      "She abandoned her plans to study abroad.",
    ],
    examplesBn: ["ঝড়ের সময় কর্মীরা জাহাজটি পরিত্যাগ করতে বাধ্য হয়েছিল।"],
    synonyms: ["forsake", "desert"],
    antonyms: ["keep", "maintain"],
    level: "B2",
    category: "Academic",
    partsOfSpeech: "verb",
  },
  {
    id: 2,
    word: "agenda",
    meaningBn: ["আলোচ্যসূচি"],
    definitionEn: "A list of items to be discussed or dealt with at a meeting.",
    definitionBn: "সভার বা বৈঠকের আলোচ্য বিষয়গুলোর তালিকা।",
    examplesEn: ["The first item on the agenda was the annual budget."],
    examplesBn: ["আলোচ্যসূচির প্রথম বিষয় ছিল বার্ষিক বাজেট।"],
    synonyms: ["schedule", "plan"],
    antonyms: [],
    level: "B2",
    category: "Business",
    partsOfSpeech: "noun",
  },
  {
    id: 3,
    word: "apartment",
    meaningBn: ["ফ্ল্যাট", "অ্যাপার্টমেন্ট"],
    definitionEn: "A set of rooms for living in, usually on one floor of a building.",
    definitionBn: "একটি ভবনের একটি তলায় অবস্থিত বসবাসের জন্য কক্ষসমষ্টি।",
    examplesEn: ["She lives in a small apartment near the university."],
    examplesBn: ["সে বিশ্ববিদ্যালয়ের কাছে একটি ছোট অ্যাপার্টমেন্টে থাকে।"],
    synonyms: ["flat", "condo"],
    antonyms: [],
    level: "A1",
    category: "Oxford3000",
    partsOfSpeech: "noun",
  },
  {
    id: 4,
    word: "attitude",
    meaningBn: ["মনোভাব", "দৃষ্টিভঙ্গি"],
    definitionEn: "The way you think and feel about someone or something.",
    definitionBn: "কোনো ব্যক্তি বা বিষয় সম্পর্কে চিন্তা ও অনুভূতির ধরন।",
    examplesEn: ["She has a positive attitude toward learning."],
    examplesBn: ["শেখার প্রতি তার ইতিবাচক মনোভাব রয়েছে।"],
    synonyms: ["outlook", "viewpoint"],
    antonyms: [],
    level: "B1",
    category: "Oxford3000",
    partsOfSpeech: "noun",
  },
  {
    id: 5,
    word: "benefit",
    meaningBn: ["সুবিধা", "লাভ"],
    definitionEn:
      "An advantage or profit gained from something, or to receive a benefit.",
    definitionBn: "কোনো কিছু থেকে অর্জিত লাভ বা সুবিধা।",
    examplesEn: [
      "Regular exercise has many health benefits.",
      "Both sides will benefit from the new agreement.",
    ],
    examplesBn: ["নিয়মিত ব্যায়ামের অনেক স্বাস্থ্য উপকারিতা রয়েছে।"],
    synonyms: ["advantage", "profit", "gain"],
    antonyms: ["disadvantage", "drawback"],
    level: "B1",
    category: "Business",
    partsOfSpeech: "noun",
  },
  {
    id: 6,
    word: "brilliant",
    meaningBn: ["উজ্জ্বল", "অসাধারণ"],
    definitionEn: "Exceptionally clever or talented; very bright or shining.",
    definitionBn: "অত্যন্ত বুদ্ধিমান বা দক্ষ; খুব উজ্জ্বল।",
    examplesEn: ["She came up with a brilliant idea for the project."],
    examplesBn: ["তিনি প্রকল্পের জন্য একটি অসাধারণ ধারণা নিয়ে এসেছিলেন।"],
    synonyms: ["intelligent", "genius", "bright"],
    antonyms: ["dim", "foolish"],
    level: "B2",
    category: "Academic",
    partsOfSpeech: "adjective",
  },
  {
    id: 7,
    word: "cafe",
    meaningBn: ["ক্যাফে", "ছোট রেস্তোরাঁ"],
    definitionEn: "A small restaurant selling light meals and drinks.",
    definitionBn: "একটি ছোট রেস্তোরাঁ যেখানে হালকা খাবার ও পানীয় বিক্রি হয়।",
    examplesEn: ["We met for coffee at a small cafe."],
    examplesBn: ["আমরা একটি ছোট ক্যাফেতে কফি খাওয়ার জন্য দেখা করেছিলাম।"],
    synonyms: ["coffee shop", "bistro"],
    antonyms: [],
    level: "A1",
    category: "Travel",
    partsOfSpeech: "noun",
  },
  {
    id: 8,
    word: "capacity",
    meaningBn: ["ক্ষমতা", "ধারণক্ষমতা"],
    definitionEn: "The maximum amount something can contain or a person can do.",
    definitionBn: "কোনো কিছু সর্বোচ্চ পরিমাণ ধারণ করার ক্ষমতা।",
    examplesEn: ["The hall is filled to capacity."],
    examplesBn: ["হলটি ধারণক্ষমতার পুরো পরিমাণে ভরা।"],
    synonyms: ["volume", "ability"],
    antonyms: ["inability"],
    level: "B2",
    category: "Academic",
    partsOfSpeech: "noun",
  },
  {
    id: 9,
    word: "celebrate",
    meaningBn: ["উদযাপন করা"],
    definitionEn: "To do something enjoyable in order to mark a happy or important event.",
    definitionBn: "একটি আনন্দদায়ক বা গুরুত্বপূর্ণ ঘটনা উদযাপনের জন্য কিছু করা।",
    examplesEn: ["We celebrated her birthday with a small party."],
    examplesBn: ["আমরা একটি ছোট পার্টির মাধ্যমে তার জন্মদিন উদযাপন করেছি।"],
    synonyms: ["commemorate", "mark"],
    antonyms: ["mourn"],
    level: "A2",
    category: "Oxford3000",
    partsOfSpeech: "verb",
  },
  {
    id: 10,
    word: "courage",
    meaningBn: ["সাহস", "নির্ভীকতা"],
    definitionEn: "The ability to do something that frightens you.",
    definitionBn: "ভয় লাগে এমন কিছু করার সামর্থ্য।",
    examplesEn: ["She showed great courage in facing the challenge."],
    examplesBn: ["চ্যালেঞ্জ মোকাবিলায় তিনি অসাধারণ সাহস দেখিয়েছেন।"],
    synonyms: ["bravery", "valour", "nerve"],
    antonyms: ["fear", "cowardice"],
    level: "B1",
    category: "Oxford3000",
    partsOfSpeech: "noun",
  },
  {
    id: 11,
    word: "dedicate",
    meaningBn: ["নিবেদন করা", "উৎসর্গ করা"],
    definitionEn: "To give a lot of time and effort to something you believe in.",
    definitionBn: "যে বিষয়ে বিশ্বাস করা হয় তাতে প্রচুর সময় ও পরিশ্রম দেওয়া।",
    examplesEn: ["She dedicated herself to helping the poor."],
    examplesBn: ["তিনি গরিবদের সাহায্যের জন্য নিজেকে নিবেদিত করেছেন।"],
    synonyms: ["devote", "commit"],
    antonyms: ["neglect"],
    level: "C1",
    category: "Academic",
    partsOfSpeech: "verb",
  },
  {
    id: 12,
    word: "eager",
    meaningBn: ["আগ্রহী", "উৎসুক"],
    definitionEn: "Wanting to do or have something very much.",
    definitionBn: "কোনো কিছু করতে বা পেতে খুব আগ্রহী।",
    examplesEn: ["The children were eager to open their presents."],
    examplesBn: ["শিশুরা তাদের উপহার খুলতে খুব আগ্রহী ছিল।"],
    synonyms: ["keen", "enthusiastic"],
    antonyms: ["reluctant", "apathetic"],
    level: "B1",
    category: "Oxford3000",
    partsOfSpeech: "adjective",
  },
  {
    id: 13,
    word: "environment",
    meaningBn: ["পরিবেশ"],
    definitionEn: "The natural world and the conditions in which people, animals and plants live.",
    definitionBn: "প্রাকৃতিক জগৎ এবং মানুষ, প্রাণী ও উদ্ভিদের বসবাসের অবস্থা।",
    examplesEn: ["We must protect the environment for future generations."],
    examplesBn: ["ভবিষ্যৎ প্রজন্মের জন্য আমাদের পরিবেশ রক্ষা করতে হবে।"],
    synonyms: ["habitat", "surroundings"],
    antonyms: [],
    level: "A2",
    category: "Academic",
    partsOfSpeech: "noun",
  },
  {
    id: 14,
    word: "flexible",
    meaningBn: ["নমনীয়", "অভিযোজনক্ষম"],
    definitionEn: "Able to change easily to suit new conditions or situations.",
    definitionBn: "নতুন পরিস্থিতি অনুযায়ী সহজে পরিবর্তিত হতে সক্ষম।",
    examplesEn: ["Our working hours are flexible."],
    examplesBn: ["আমাদের কাজের সময় নমনীয়।"],
    synonyms: ["adaptable", "elastic"],
    antonyms: ["rigid", "inflexible"],
    level: "B2",
    category: "Business",
    partsOfSpeech: "adjective",
  },
  {
    id: 15,
    word: "generate",
    meaningBn: ["উত্পন্ন করা", "সৃষ্টি করা"],
    definitionEn: "To produce or create something, especially power or ideas.",
    definitionBn: "কিছু উত্পাদন বা সৃষ্টি করা, বিশেষত শক্তি বা ধারণা।",
    examplesEn: ["The dam generates electricity for the whole region."],
    examplesBn: ["বাঁধটি পুরো অঞ্চলের জন্য বিদ্যুৎ উত্পন্ন করে।"],
    synonyms: ["produce", "create"],
    antonyms: ["consume", "destroy"],
    level: "B2",
    category: "Business",
    partsOfSpeech: "verb",
  },
  {
    id: 16,
    word: "genuine",
    meaningBn: ["আসল", "খাঁটি"],
    definitionEn: "Truly what something is said to be; real and sincere.",
    definitionBn: "যা বলা হয় সত্যিই তা; বাস্তব ও আন্তরিক।",
    examplesEn: ["The painting is a genuine masterpiece."],
    examplesBn: ["চিত্রকর্মটি একটি আসল মাস্টারপিস।"],
    synonyms: ["authentic", "real"],
    antonyms: ["fake", "counterfeit"],
    level: "C1",
    category: "Academic",
    partsOfSpeech: "adjective",
  },
  {
    id: 17,
    word: "harbor",
    meaningBn: ["আশ্রয়", "বন্দর"],
    definitionEn: "A sheltered area where ships can dock, or to shelter someone.",
    definitionBn: "যেখানে জাহাজ ভিড়তে পারে এমন আশ্রয়স্থল।",
    examplesEn: ["The fishing boats returned to the harbor at sunset."],
    examplesBn: ["সূর্যাস্তের সময় মাছ ধরার নৌকাগুলো বন্দরে ফিরে আসে।"],
    synonyms: ["port", "haven"],
    antonyms: [],
    level: "B1",
    category: "Travel",
    partsOfSpeech: "noun",
  },
  {
    id: 18,
    word: "improve",
    meaningBn: ["উন্নতি করা", "উন্নত করা"],
    definitionEn: "To make or become better.",
    definitionBn: "কাউকে বা কিছুকে ভালো করা বা হওয়া।",
    examplesEn: ["Reading every day will improve your vocabulary."],
    examplesBn: ["প্রতিদিন পড়াশোনা আপনার শব্দভাণ্ডার উন্নত করবে।"],
    synonyms: ["enhance", "better"],
    antonyms: ["worsen", "decline"],
    level: "A2",
    category: "Oxford3000",
    partsOfSpeech: "verb",
  },
  {
    id: 19,
    word: "influence",
    meaningBn: ["প্রভাব"],
    definitionEn: "The power to affect how someone or something develops or behaves.",
    definitionBn: "কাউকে বা কিছুকে প্রভাবিত করার ক্ষমতা।",
    examplesEn: ["Her teacher had a strong influence on her career."],
    examplesBn: ["তার শিক্ষক তার কর্মজীবনে দৃঢ় প্রভাব ফেলেছিলেন।"],
    synonyms: ["impact", "effect"],
    antonyms: [],
    level: "B2",
    category: "Academic",
    partsOfSpeech: "noun",
  },
  {
    id: 20,
    word: "journey",
    meaningBn: ["যাত্রা", "ভ্রমণ"],
    definitionEn: "An act of traveling from one place to another, especially a long one.",
    definitionBn: "এক স্থান থেকে অন্য স্থানে ভ্রমণ, বিশেষত দীর্ঘ ভ্রমণ।",
    examplesEn: ["It was a long journey by train across the country."],
    examplesBn: ["দেশের ওপারে ট্রেনে দীর্ঘ যাত্রা ছিল।"],
    synonyms: ["trip", "voyage", "expedition"],
    antonyms: [],
    level: "B1",
    category: "Travel",
    partsOfSpeech: "noun",
  },
  {
    id: 21,
    word: "knowledge",
    meaningBn: ["জ্ঞান", "বিদ্যা"],
    definitionEn: "The understanding and information about a subject that you have in your mind.",
    definitionBn: "একটি বিষয় সম্পর্কে মনের মধ্যে থাকা বোঝাপড়া ও তথ্য।",
    examplesEn: ["She has a deep knowledge of world history."],
    examplesBn: ["বিশ্ব ইতিহাস সম্পর্কে তার গভীর জ্ঞান রয়েছে।"],
    synonyms: ["understanding", "expertise"],
    antonyms: ["ignorance"],
    level: "A2",
    category: "Academic",
    partsOfSpeech: "noun",
  },
  {
    id: 22,
    word: "lucrative",
    meaningBn: ["লাভজনক", "আয়কর"],
    definitionEn: "Producing a great deal of profit.",
    definitionBn: "প্রচুর মুনাফা উত্পাদনকারী।",
    examplesEn: ["It is a lucrative business opportunity."],
    examplesBn: ["এটি একটি লাভজনক ব্যবসায়িক সুযোগ।"],
    synonyms: ["profitable", "rewarding"],
    antonyms: ["unprofitable", "unrewarding"],
    level: "C1",
    category: "Business",
    partsOfSpeech: "adjective",
  },
  {
    id: 23,
    word: "maintain",
    meaningBn: ["বজায় রাখা", "রক্ষণাবেক্ষণ করা"],
    definitionEn: "To keep something in good condition or keep it going.",
    definitionBn: "কিছু ভালো অবস্থায় রাখা বা চালিয়ে যাওয়া।",
    examplesEn: ["It is important to maintain a healthy diet."],
    examplesBn: ["সুষম খাদ্যাভ্যাস বজায় রাখা গুরুত্বপূর্ণ।"],
    synonyms: ["preserve", "sustain"],
    antonyms: ["neglect", "abandon"],
    level: "B2",
    category: "Academic",
    partsOfSpeech: "verb",
  },
  {
    id: 24,
    word: "nourish",
    meaningBn: ["পুষ্ট করা", "লালন করা"],
    definitionEn: "To provide food or the right conditions for growth and health.",
    definitionBn: "বৃদ্ধি ও স্বাস্থ্যের জন্য খাদ্য বা উপযুক্ত অবস্থা প্রদান করা।",
    examplesEn: ["Breast milk nourishes the baby."],
    examplesBn: ["মায়ের দুধ শিশুকে পুষ্ট করে।"],
    synonyms: ["feed", "sustain"],
    antonyms: ["starve"],
    level: "C1",
    category: "Oxford3000",
    partsOfSpeech: "verb",
  },
  {
    id: 25,
    word: "opportunity",
    meaningBn: ["সুযোগ", "অবসর"],
    definitionEn: "A set of circumstances that makes it possible to do something.",
    definitionBn: "কোনো কিছু করার সম্ভাবনাময় পরিস্থিতি।",
    examplesEn: ["This is a great opportunity to improve your English."],
    examplesBn: ["আপনার ইংরেজি উন্নত করার এটি একটি বড় সুযোগ।"],
    synonyms: ["chance", "prospect"],
    antonyms: ["miss"],
    level: "B1",
    category: "Business",
    partsOfSpeech: "noun",
  },
  {
    id: 26,
    word: "persuade",
    meaningBn: ["বোঝানো", "প্ররোচিত করা"],
    definitionEn: "To make someone agree to do something by giving good reasons.",
    definitionBn: "যুক্তিসহ ভালো কারণ দেখিয়ে কাউকে রাজি করানো।",
    examplesEn: ["He persuaded me to join the team."],
    examplesBn: ["সে আমাকে দলে যোগ দেওয়ার জন্য প্ররোচিত করেছিল।"],
    synonyms: ["convince", "influence"],
    antonyms: ["dissuade"],
    level: "B2",
    category: "Academic",
    partsOfSpeech: "verb",
  },
  {
    id: 27,
    word: "prosperous",
    meaningBn: ["সমৃদ্ধ", "উন্নতিশীল"],
    definitionEn: "Successful and rich.",
    definitionBn: "সফল ও ধনী।",
    examplesEn: ["The city became prosperous through trade."],
    examplesBn: ["বাণিজ্যের মাধ্যমে শহরটি সমৃদ্ধ হয়েছে।"],
    synonyms: ["affluent", "wealthy"],
    antonyms: ["poor", "destitute"],
    level: "C1",
    category: "Business",
    partsOfSpeech: "adjective",
  },
  {
    id: 28,
    word: "resilient",
    meaningBn: ["স্থিতিস্থাপক", "সহনশীল"],
    definitionEn:
      "Able to recover quickly from difficult conditions.",
    definitionBn: "কঠিন পরিস্থিতি থেকে দ্রুত ফিরে আসতে সক্ষম।",
    examplesEn: ["Children are often more resilient than adults."],
    examplesBn: ["শিশুরা প্রায়ই প্রাপ্তবয়স্কদের চেয়ে বেশি স্থিতিস্থাপক।"],
    synonyms: ["tough", "robust"],
    antonyms: ["fragile", "weak"],
    level: "C1",
    category: "Academic",
    partsOfSpeech: "adjective",
  },
  {
    id: 29,
    word: "salary",
    meaningBn: ["বেতন", "মাইনে"],
    definitionEn: "A fixed regular payment made by an employer to an employee.",
    definitionBn: "নিয়োগকর্তা কর্তৃক কর্মচারীকে দেওয়া নিয়মিত নির্দিষ্ট পেমেন্ট।",
    examplesEn: ["He receives a good salary for his work."],
    examplesBn: ["তার কাজের জন্য সে ভালো বেতন পায়।"],
    synonyms: ["wage", "pay"],
    antonyms: [],
    level: "A2",
    category: "Business",
    partsOfSpeech: "noun",
  },
  {
    id: 30,
    word: "sustainable",
    meaningBn: ["টেকসই", "পরিবেশবান্ধব"],
    definitionEn: "Able to be maintained at a certain rate or level, or without harming the environment.",
    definitionBn: "পরিবেশের ক্ষতি না করে নির্দিষ্ট হারে বজায় রাখার উপযোগী।",
    examplesEn: ["We need sustainable sources of energy."],
    examplesBn: ["আমাদের টেকসই শক্তির উৎস দরকার।"],
    synonyms: ["maintainable", "viable"],
    antonyms: ["unsustainable"],
    level: "C1",
    category: "Academic",
    partsOfSpeech: "adjective",
  },
  {
    id: 31,
    word: "temporary",
    meaningBn: ["অস্থায়ী", "সাময়িক"],
    definitionEn: "Lasting for only a limited period of time.",
    definitionBn: "কেবল সীমিত সময়ের জন্য স্থায়ী।",
    examplesEn: ["She has a temporary job until summer."],
    examplesBn: ["গ্রীষ্ম পর্যন্ত তার অস্থায়ী চাকরি আছে।"],
    synonyms: ["provisional", "transient"],
    antonyms: ["permanent", "lasting"],
    level: "B2",
    category: "Business",
    partsOfSpeech: "adjective",
  },
  {
    id: 32,
    word: "thrive",
    meaningBn: ["সমৃদ্ধ হওয়া", "বৃদ্ধি পাওয়া"],
    definitionEn: "To grow, develop, or be successful.",
    definitionBn: "বেড়ে ওঠা, বিকশিত হওয়া বা সফল হওয়া।",
    examplesEn: ["Businesses thrive in a stable economy."],
    examplesBn: ["স্থিতিশীল অর্থনীতিতে ব্যবসা সমৃদ্ধ হয়।"],
    synonyms: ["flourish", "prosper"],
    antonyms: ["decline", "struggle"],
    level: "C1",
    category: "Business",
    partsOfSpeech: "verb",
  },
  {
    id: 33,
    word: "undertake",
    meaningBn: ["দায়িত্ব নেওয়া", "সম্পন্ন করা"],
    definitionEn: "To take responsibility for doing a task or job.",
    definitionBn: "একটি কাজ বা দায়িত্ব করার দায়িত্ব গ্রহণ করা।",
    examplesEn: ["The government will undertake a new road project."],
    examplesBn: ["সরকার একটি নতুন সড়ক প্রকল্পের দায়িত্ব নেবে।"],
    synonyms: ["take on", "assume"],
    antonyms: ["decline"],
    level: "C1",
    category: "Academic",
    partsOfSpeech: "verb",
  },
  {
    id: 34,
    word: "vivid",
    meaningBn: ["জীবন্ত", "প্রাণবন্ত"],
    definitionEn: "Producing powerful feelings or strong, clear images in the mind.",
    definitionBn: "মনে শক্তিশালী অনুভূতি বা স্পষ্ট চিত্র তৈরি করে এমন।",
    examplesEn: ["She told a vivid description of her journey."],
    examplesBn: ["সে তার যাত্রার একটি প্রাণবন্ত বর্ণনা দিল।"],
    synonyms: ["graphic", "lively"],
    antonyms: ["dull", "vague"],
    level: "C1",
    category: "Oxford3000",
    partsOfSpeech: "adjective",
  },
  {
    id: 35,
    word: "wander",
    meaningBn: ["ঘুরে বেড়ানো"],
    definitionEn: "To walk around slowly without a clear purpose or direction.",
    definitionBn: "স্পষ্ট উদ্দেশ্য বা দিক ছাড়া ধীরে ধীরে ঘোরা।",
    examplesEn: ["We wandered through the old town all afternoon."],
    examplesBn: ["সারাক্ষণ আমরা পুরনো শহরে ঘুরে বেড়ালাম।"],
    synonyms: ["roam", "stroll"],
    antonyms: ["stay"],
    level: "B1",
    category: "Travel",
    partsOfSpeech: "verb",
  },
  {
    id: 36,
    word: "zest",
    meaningBn: ["উদ্যম", "উৎসাহ"],
    definitionEn: "Great enthusiasm and energy.",
    definitionBn: "সর্বোচ্চ উৎসাহ ও শক্তি।",
    examplesEn: ["He tackled every task with great zest."],
    examplesBn: ["সে প্রতিটি কাজ অনেক উৎসাহ নিয়ে করেছে।"],
    synonyms: ["enthusiasm", "passion"],
    antonyms: ["apathy"],
    level: "C2",
    category: "Idioms",
    partsOfSpeech: "noun",
  },
];
