import { TemplateDefinition } from "../types";

export const DEFAULT_QUIZ_POSTER_TEMPLATE: TemplateDefinition = {
  version: "1.0",
  width: 1080,
  height: 1350,
  backgroundColor: "#09090b", // Sleek dark aesthetic
  backgroundFit: "cover",
  elements: [
    // Top gradient accent card
    {
      id: "header-bg",
      type: "shape",
      shapeType: "rectangle",
      x: 60,
      y: 60,
      width: 960,
      height: 140,
      fill: "#18181b",
      borderRadius: 24,
      stroke: "#27272a",
      strokeWidth: 2,
      zIndex: 1,
    },
    // Branding Badge
    {
      id: "brand-title",
      type: "text",
      content: "ZERO ENGLISH",
      x: 100,
      y: 90,
      width: 400,
      height: 40,
      fontFamily: "Inter",
      fontSize: 28,
      fontWeight: 800,
      color: "#38bdf8",
      textAlign: "left",
      zIndex: 2,
    },
    {
      id: "brand-tagline",
      type: "text",
      content: "DAILY ENGLISH QUIZ",
      x: 100,
      y: 136,
      width: 400,
      height: 30,
      fontFamily: "Inter",
      fontSize: 16,
      fontWeight: 600,
      color: "#a1a1aa",
      textAlign: "left",
      letterSpacing: 2,
      zIndex: 2,
    },
    // Quiz Number Badge
    {
      id: "quiz-badge-bg",
      type: "shape",
      shapeType: "rectangle",
      x: 820,
      y: 96,
      width: 160,
      height: 52,
      fill: "#27272a",
      borderRadius: 14,
      stroke: "#3f3f46",
      strokeWidth: 1,
      zIndex: 2,
    },
    {
      id: "quiz-number",
      type: "dynamic-text",
      field: "{{quiz.id}}",
      content: "Quiz #{{quiz.id}}",
      x: 820,
      y: 108,
      width: 160,
      height: 30,
      fontFamily: "Inter",
      fontSize: 20,
      fontWeight: 700,
      color: "#ffffff",
      textAlign: "center",
      zIndex: 3,
    },

    // Main Question Card
    {
      id: "question-card",
      type: "shape",
      shapeType: "rectangle",
      x: 60,
      y: 230,
      width: 960,
      height: 320,
      fill: "#18181b",
      borderRadius: 28,
      stroke: "#38bdf8",
      strokeWidth: 2,
      zIndex: 1,
    },
    {
      id: "question-label",
      type: "text",
      content: "QUESTION",
      x: 100,
      y: 260,
      width: 200,
      height: 30,
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: 700,
      color: "#38bdf8",
      textAlign: "left",
      letterSpacing: 3,
      zIndex: 2,
    },
    {
      id: "question-text",
      type: "dynamic-text",
      field: "{{quiz.question}}",
      content: "{{quiz.question}}",
      x: 100,
      y: 300,
      width: 880,
      height: 220,
      fontFamily: "Hind Siliguri",
      fontSize: 38,
      fontWeight: 700,
      color: "#ffffff",
      textAlign: "left",
      lineHeight: 1.35,
      zIndex: 2,
    },

    // Option A
    {
      id: "opt-a-bg",
      type: "shape",
      shapeType: "rectangle",
      x: 60,
      y: 580,
      width: 465,
      height: 120,
      fill: "#18181b",
      borderRadius: 20,
      stroke: "#27272a",
      strokeWidth: 2,
      zIndex: 1,
    },
    {
      id: "opt-a-letter",
      type: "text",
      content: "A",
      x: 85,
      y: 618,
      width: 44,
      height: 44,
      fontFamily: "Inter",
      fontSize: 22,
      fontWeight: 800,
      color: "#38bdf8",
      textAlign: "center",
      backgroundColor: "#27272a",
      borderRadius: 10,
      padding: 6,
      zIndex: 2,
    },
    {
      id: "opt-a-text",
      type: "dynamic-text",
      field: "{{quiz.optionA}}",
      content: "{{quiz.optionA}}",
      x: 145,
      y: 622,
      width: 360,
      height: 60,
      fontFamily: "Hind Siliguri",
      fontSize: 24,
      fontWeight: 600,
      color: "#f4f4f5",
      textAlign: "left",
      zIndex: 2,
    },

    // Option B
    {
      id: "opt-b-bg",
      type: "shape",
      shapeType: "rectangle",
      x: 555,
      y: 580,
      width: 465,
      height: 120,
      fill: "#18181b",
      borderRadius: 20,
      stroke: "#27272a",
      strokeWidth: 2,
      zIndex: 1,
    },
    {
      id: "opt-b-letter",
      type: "text",
      content: "B",
      x: 580,
      y: 618,
      width: 44,
      height: 44,
      fontFamily: "Inter",
      fontSize: 22,
      fontWeight: 800,
      color: "#38bdf8",
      textAlign: "center",
      backgroundColor: "#27272a",
      borderRadius: 10,
      padding: 6,
      zIndex: 2,
    },
    {
      id: "opt-b-text",
      type: "dynamic-text",
      field: "{{quiz.optionB}}",
      content: "{{quiz.optionB}}",
      x: 640,
      y: 622,
      width: 360,
      height: 60,
      fontFamily: "Hind Siliguri",
      fontSize: 24,
      fontWeight: 600,
      color: "#f4f4f5",
      textAlign: "left",
      zIndex: 2,
    },

    // Option C
    {
      id: "opt-c-bg",
      type: "shape",
      shapeType: "rectangle",
      x: 60,
      y: 720,
      width: 465,
      height: 120,
      fill: "#18181b",
      borderRadius: 20,
      stroke: "#27272a",
      strokeWidth: 2,
      zIndex: 1,
    },
    {
      id: "opt-c-letter",
      type: "text",
      content: "C",
      x: 85,
      y: 758,
      width: 44,
      height: 44,
      fontFamily: "Inter",
      fontSize: 22,
      fontWeight: 800,
      color: "#38bdf8",
      textAlign: "center",
      backgroundColor: "#27272a",
      borderRadius: 10,
      padding: 6,
      zIndex: 2,
    },
    {
      id: "opt-c-text",
      type: "dynamic-text",
      field: "{{quiz.optionC}}",
      content: "{{quiz.optionC}}",
      x: 145,
      y: 762,
      width: 360,
      height: 60,
      fontFamily: "Hind Siliguri",
      fontSize: 24,
      fontWeight: 600,
      color: "#f4f4f5",
      textAlign: "left",
      zIndex: 2,
    },

    // Option D
    {
      id: "opt-d-bg",
      type: "shape",
      shapeType: "rectangle",
      x: 555,
      y: 720,
      width: 465,
      height: 120,
      fill: "#18181b",
      borderRadius: 20,
      stroke: "#27272a",
      strokeWidth: 2,
      zIndex: 1,
    },
    {
      id: "opt-d-letter",
      type: "text",
      content: "D",
      x: 580,
      y: 758,
      width: 44,
      height: 44,
      fontFamily: "Inter",
      fontSize: 22,
      fontWeight: 800,
      color: "#38bdf8",
      textAlign: "center",
      backgroundColor: "#27272a",
      borderRadius: 10,
      padding: 6,
      zIndex: 2,
    },
    {
      id: "opt-d-text",
      type: "dynamic-text",
      field: "{{quiz.optionD}}",
      content: "{{quiz.optionD}}",
      x: 640,
      y: 762,
      width: 360,
      height: 60,
      fontFamily: "Hind Siliguri",
      fontSize: 24,
      fontWeight: 600,
      color: "#f4f4f5",
      textAlign: "left",
      zIndex: 2,
    },

    // Explanation / Answer Reveal Card
    {
      id: "answer-box",
      type: "shape",
      shapeType: "rectangle",
      x: 60,
      y: 865,
      width: 960,
      height: 185,
      fill: "#052e16",
      borderRadius: 20,
      stroke: "#22c55e",
      strokeWidth: 2,
      zIndex: 1,
    },
    {
      id: "answer-title",
      type: "text",
      content: "CORRECT ANSWER",
      x: 95,
      y: 885,
      width: 300,
      height: 25,
      fontFamily: "Inter",
      fontSize: 14,
      fontWeight: 700,
      color: "#4ade80",
      textAlign: "left",
      letterSpacing: 2,
      zIndex: 2,
    },
    {
      id: "answer-val",
      type: "dynamic-text",
      field: "{{quiz.answer}}",
      content: "{{quiz.answer}}",
      x: 95,
      y: 915,
      width: 890,
      height: 40,
      fontFamily: "Hind Siliguri",
      fontSize: 28,
      fontWeight: 700,
      color: "#ffffff",
      textAlign: "left",
      zIndex: 2,
    },
    {
      id: "explanation-val",
      type: "dynamic-text",
      field: "{{quiz.explanation}}",
      content: "{{quiz.explanation}}",
      x: 95,
      y: 965,
      width: 890,
      height: 70,
      fontFamily: "Hind Siliguri",
      fontSize: 18,
      fontWeight: 400,
      color: "#bbf7d0",
      textAlign: "left",
      zIndex: 2,
    },

    // Bottom Footer Card with QR Code
    {
      id: "footer-bg",
      type: "shape",
      shapeType: "rectangle",
      x: 60,
      y: 1075,
      width: 960,
      height: 215,
      fill: "#18181b",
      borderRadius: 24,
      stroke: "#27272a",
      strokeWidth: 2,
      zIndex: 1,
    },
    {
      id: "footer-qr",
      type: "qrcode",
      field: "{{quiz.url}}",
      x: 95,
      y: 1100,
      width: 165,
      height: 165,
      darkColor: "#000000",
      lightColor: "#ffffff",
      zIndex: 2,
    },
    {
      id: "scan-heading",
      type: "text",
      content: "Scan QR to Solve & Learn",
      x: 290,
      y: 1120,
      width: 500,
      height: 35,
      fontFamily: "Inter",
      fontSize: 26,
      fontWeight: 800,
      color: "#ffffff",
      textAlign: "left",
      zIndex: 2,
    },
    {
      id: "scan-desc",
      type: "text",
      content: "Join thousands of learners mastering vocabulary, grammar and quizzes on zeroenglish.org",
      x: 290,
      y: 1165,
      width: 680,
      height: 50,
      fontFamily: "Inter",
      fontSize: 18,
      fontWeight: 400,
      color: "#a1a1aa",
      textAlign: "left",
      zIndex: 2,
    },
    {
      id: "category-tag",
      type: "dynamic-text",
      field: "{{quiz.category}}",
      content: "Topic: {{quiz.category}}  •  zeroenglish.org",
      x: 290,
      y: 1230,
      width: 680,
      height: 30,
      fontFamily: "Inter",
      fontSize: 16,
      fontWeight: 600,
      color: "#38bdf8",
      textAlign: "left",
      zIndex: 2,
    },
  ],
};
